<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>login</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <form method="post" action="logic/login.php">
            <fieldset>
                <label for="email">
                    email
                </label>
                <input type="email" name="email" id="email" />
            </fieldset>
            <fieldset>
                <label for="password">
                    mot de passe
                </label>
                <input type="password" name="password" id="password" />
            </fieldset>
            <fieldset>
                <button type="submit">Envoyer</button>
            </fieldset>
        </form>
    </body>
</html>