<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Demo Formulaires</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <form method="post" action="logic/register.php">
            <fieldset>
                <label for="firstName">
                    Prénom
                </label>
                <input type="text" name="firstName" id="firstName" />
            </fieldset>
            <fieldset>
                <label for="lastName">
                    Nom
                </label>
                <input type="text" name="lastName" id="lastName" />
            </fieldset>
            <fieldset>
                <label for="email">
                    email
                </label>
                <input type="email" name="email" id="email" />
            </fieldset>
            <fieldset>
                <label for="password">
                    mot de passe
                </label>
                <input type="password" name="password" id="password" />
            </fieldset>
            <fieldset>
                <button type="submit">Envoyer</button>
            </fieldset>
        </form>
    </body>
</html>